-- ========================================================
-- Auto-generated data migration from legacy python sitenav (single source: scripts/legacy/site_item.sql)
-- Generated At: 2026-07-20T01:39:17.633Z
-- This is the ONLY script that needs to be run to fully sync local/prod data.
-- Do not hand-edit — regenerate via `npm run db:migrate-legacy:generate`.
-- ========================================================

-- Clean legacy table data for idempotency
DELETE FROM sites;
DELETE FROM categories;

-- Seed D1 AUTOINCREMENT floor for sites table (10,000,000)
INSERT INTO sites (id, category_id, name, url, status) VALUES (9999999, NULL, '__seed_floor__', 'about:blank', 0);
DELETE FROM sites WHERE id = 9999999;

-- ========================================================
-- PHASE 0: Create the index/other/h5 root buckets
-- These are real category rows (pid IS NULL) that the v1 adapter layer
-- reads back via name, replacing the old rootId>=2000 ID-threshold guess.
-- No explicit id: on a freshly emptied table these autoincrement to 1/2/3,
-- which never collides with the preserved legacy ids (1000+/2000+) below.
-- ========================================================

INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'index', 0, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'other', 1, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'h5', 2, 1, 1, 1, strftime('%s', 'now') * 1000);

-- ========================================================
-- PHASE 1: Populate categories (preserving original raw IDs)
-- Top-level rows (original pId = 0) are reparented under the matching
-- index/other/h5 root created in PHASE 0 instead of staying pid = NULL.
-- ========================================================

INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1000, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Common Sites', 1000, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1100, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Local Sites', 1100, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1200, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Dev20 Sites', 1200, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1210, 1200, 'develop', 1210, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1220, 1200, 'QA', 1220, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1300, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Test Sites', 1300, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1400, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Prod Sites', 1400, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2000, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '常用', 2000, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2001, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '学习', 2001, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2002, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '影视', 2002, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2003, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '杂类', 2003, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2004, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '系统', 2004, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2005, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '生活', 2005, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2022, 2001, '代码仓库， 免费建站', 2022, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2026, 2001, 'Database', 2026, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2027, 2001, 'Mock Api', 2027, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2030, 2001, '音图资源', 2030, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2125, (SELECT id FROM categories WHERE name = 'h5' AND pid IS NULL LIMIT 1), '常用', 1, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2126, (SELECT id FROM categories WHERE name = 'h5' AND pid IS NULL LIMIT 1), '文娱', 2, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2127, (SELECT id FROM categories WHERE name = 'h5' AND pid IS NULL LIMIT 1), '求知', 3, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2134, (SELECT id FROM categories WHERE name = 'h5' AND pid IS NULL LIMIT 1), '工具', 4, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2136, (SELECT id FROM categories WHERE name = 'h5' AND pid IS NULL LIMIT 1), '搬砖', 5, 0, 0, 0, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2140, 2125, '兰洋科技', 10, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2143, 2126, '18+', 100, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2158, 2134, 'Cloudflare', 5, 1, 1, 1, strftime('%s', 'now') * 1000);

-- ========================================================
-- PHASE 2: Populate sites (applying SITE_ID_OFFSET = 10000000)
-- Top-level sites (original pId = 0) are reparented under the matching
-- index/other/h5 root the same way top-level categories are in PHASE 1 —
-- category_id = 0 doesn't reference any real category.
-- ========================================================

INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001010, 1000, 'Jenkins', 'http://121.196.104.20:8888/', '', NULL, 1, 1, 1010, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001020, 1000, '禅道', 'http://192.168.2.180:82/zentao/my.html', '', NULL, 1, 1, 1020, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001030, 1000, '墨刀', 'https://modao.cc/team/splbgnpgz7muqiei/folder/tel2zzhemdlh8vgayk', '', NULL, 1, 1, 1030, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001040, 1000, '邮箱', 'http://mail.lanyang.com/', '', NULL, 1, 1, 1040, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001050, 1000, 'Gitblit', 'http://192.168.2.180:8808/', '', NULL, 1, 1, 1050, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001060, 1000, '开发任务汇总', 'https://www.kdocs.cn/wo/sl/v344KoRZ?app_id=2wd4E4bxTOHihwkwkvaNGN', '', NULL, 1, 1, 1060, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001070, 1000, '物联网秤项目任务', 'https://kdocs.cn/l/cogElwjqE2yZ', '', NULL, 1, 1, 1070, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001080, 1000, '发布申请表', 'https://kdocs.cn/l/crwpEMnJI6Lt', '', NULL, 1, 1, 1080, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001110, 1100, 'IotLpg.Web', 'http://localhost:8012/IotLpg.Web/index.aspx', '', NULL, 1, 1, 1110, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001120, 1100, 'IotLpg.Sale.App.Api', 'http://localhost:8012/iot.sale.app.api/swagger/index.html', '', NULL, 1, 1, 1120, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001130, 1100, 'IotLpg.Sale.App.Api(Sejil Log)', 'http://localhost:8012/iot.sale.app.api/Sejil', '', NULL, 1, 1, 1130, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001140, 1100, 'trunklpg', 'http://localhost:8012/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1140, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001150, 1100, 'trunklpg - 呼叫配送管理系统', 'http://localhost:8012/dev.trunklpg/SysManage/index.aspx', '', NULL, 1, 1, 1150, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001160, 1100, '09WebAPI.WebApi', 'http://localhost:8012/dev.webapi/swagger', '', NULL, 1, 1, 1160, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001170, 1100, 'SaaSAPPlpg', 'http://localhost:8012/dev.saasapplpg', '', NULL, 1, 1, 1170, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001180, 1100, 'OperationLogs', 'http://localhost:8012/dev.trunklpg/SaasHTML5/System/OperationLogs.html', '', NULL, 1, 1, 1180, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001211, 1210, 'dev.trunklpg', 'https://test.117915.com/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1211, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001212, 1210, 'dev.webapi', 'https://test.117915.com/dev.webapi/swagger', '', NULL, 1, 1, 1212, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001213, 1210, 'dev.saasapplpg', 'https://test.117915.com/dev.saasapplpg/', '', NULL, 1, 1, 1213, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001221, 1220, 'dev.trunklpg', 'http://121.196.104.20:8013/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1221, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001222, 1220, 'dev.webapi', 'http://121.196.104.20:8013/dev.webapi/swagger', '', NULL, 1, 1, 1222, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001223, 1220, 'dev.saasapplpg', 'http://121.196.104.20:8013/dev.saasapplpg/', '', NULL, 1, 1, 1223, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001310, 1300, 'iotlpg', 'http://iotlpg.117915.com/testclient/Login.aspx', '', NULL, 1, 1, 1310, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001320, 1300, 'iotlpg.saleapp.api', 'https://iotlpg.117915.com/iot.weigh.webapi.testsaleapp/swagger/index.html', '', NULL, 1, 1, 1320, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001330, 1300, '气瓶安全信息化管理系统', 'http://www.117915.cn:99/', '', NULL, 1, 1, 1330, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001340, 1300, 'trunklpg', 'https://lpg.117915.com/testlpg/home/default.aspx', '', NULL, 1, 1, 1340, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001350, 1300, 'trunklpg.SysManage', 'https://lpg.117915.com/testlpg/sysmanage/index.aspx', '', NULL, 1, 1, 1350, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001410, 1400, 'iotlpg', 'http://iotlpg.117915.com/client/Login.aspx', '', NULL, 1, 1, 1410, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001420, 1400, 'iotlpg.saleapp.api', 'https://iotlpg.117915.com/iot.weigh.webapi.saleapp/swagger/index.html', '', NULL, 1, 1, 1420, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001430, 1400, 'iotlpg.saleapp.api logs', 'https://iotlpg.117915.com/iot.weigh.webapi.saleapp/sejil', '', NULL, 1, 1, 1430, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001440, 1400, 'dcc.PublishCompConnChanged', 'http://iotlpg.117915.com/iot.weigh.dcc/Ajax/DccClient/PublishCompConnChanged.ashx', '', NULL, 1, 1, 1440, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001450, 1400, 'trunklpg', 'https://lpg.117915.com/lpg/Login.aspx', '', NULL, 1, 1, 1450, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001460, 1400, 'trunklpg.SysManage', 'https://lpg.117915.com/lpg/sysmanage/index.aspx', '', NULL, 1, 1, 1460, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002006, 2000, '电影推荐 · MVCAT', 'https://www.mvcat.com/', '', NULL, 1, 1, 2006, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002008, 2000, '编程工具', 'https://masuit.com/cat/7', '', NULL, 1, 1, 2008, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002009, 2000, 'Software - 厘米天空', 'http://www.cmsky.com/', '', NULL, 1, 1, 2009, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002010, 2000, '吾爱破解', 'https://www.52pojie.cn/', 'dfg727/aB...6', NULL, 1, 1, 2010, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002011, 2000, '图怪兽作图神器', 'https://818ps.com/', '是一个在线ps图片 海报 编辑器,', NULL, 1, 1, 2011, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002013, 2000, '书享家', 'http://shuxiangjia.cn/', '', NULL, 1, 1, 2013, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002015, 2000, 'fuliba', 'https://fuliba2023.net', '搞笑图', NULL, 1, 1, 2015, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002017, 2000, '远景', 'http://bbs.pcbeta.com/', 'ifelse01/Aa123456', NULL, 1, 1, 2017, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002018, 2000, '威锋', 'https://bbs.feng.com/', '1581.../aB...', NULL, 1, 1, 2018, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002020, 2000, 'ClashNode', 'https://clashfree.eu.org/', '', NULL, 1, 1, 2020, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002021, 2001, 'Net Framework', 'https://www.microsoft.com/net/download/visual-studio-sdks/', '', NULL, 1, 1, 2021, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002023, 2001, 'sendgrid', 'https://app.sendgrid.com/login', 'ifelse01/abc..@123..', NULL, 1, 1, 2023, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002024, 2001, 'CSDN论坛', 'http://forum.csdn.net/BList/DotNET/EssentialList', 'abc..@123..', NULL, 1, 1, 2024, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002025, 2001, 'dfg727 博客园', 'http://www.cnblogs.com/dfg727/', '', NULL, 1, 1, 2025, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002028, 2001, 'ProcessOn - 在线作图', 'https://www.processon.com/', 'QQ Login', NULL, 1, 1, 2028, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002029, 2001, 'BootCDN - 在CDN 加速服务', 'https://www.bootcdn.cn/', '前端开源项目 CDN 加速服务 ', NULL, 1, 1, 2029, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002031, 2001, 'Docker 从入门到实践 Search', 'https://vuepress.mirror.docker-practice.com/image/dockerfile/', '', NULL, 1, 1, 2031, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002032, 2022, '免费建站 - 基于github...', 'https://app.netlify.com/account/sites', '', NULL, 1, 1, 2032, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002033, 2022, 'CodeSandbox - 托管编码平台', 'https://codesandbox.io/', '', NULL, 1, 1, 2033, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002034, 2022, 'glitch - 托管编码平台', 'https://glitch.com/', '', NULL, 1, 1, 2034, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002035, 2022, 'replit - 托管编码平台', 'https://replit.com/', '', NULL, 1, 1, 2035, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002036, 2022, 'RiouxSVN', 'https://riouxsvn.com', '', NULL, 1, 1, 2036, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002037, 2022, 'SourceForge.net', 'https://sourceforge.net/account/login.php', '', NULL, 1, 1, 2037, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002038, 2022, 'codeplex.com', 'https://workspaces.codeplex.com/SourceControl/latest', '', NULL, 1, 1, 2038, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002039, 2022, 'ifelse01  GitHub', 'https://github.com/ifelse01', '', NULL, 1, 1, 2039, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002040, 2022, '代码托管 - 开源中国社区', 'https://git.oschina.net/ifelse01', '', NULL, 1, 1, 2040, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002041, 2026, 'JackDB - 在线各种数据库', 'https://app.jackdb.com/', 'QQ Login', NULL, 1, 1, 2041, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002042, 2026, 'db4free.net  MySQL', 'http://db4free.net/d4f_apply.php', '', NULL, 1, 1, 2042, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002043, 2026, '云数据库 - Bmob', 'http://www.bmob.cn/', '', NULL, 1, 1, 2043, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002044, 2027, 'DOClever', 'http://doclever.cn/controller/index/index.html', 'dfg727', NULL, 1, 1, 2044, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002045, 2027, 'rap2-taobao', 'rap2.taobao.org', '2167162@qq.com', NULL, 1, 1, 2045, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002046, 2027, 'easy-mock', 'https://www.easy-mock.com', '', NULL, 1, 1, 2046, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002047, 2030, '好图网 - 提供最优秀的图标下载', 'http://www.haotu.net/icon/179594/todo', '', NULL, 1, 1, 2047, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002048, 2030, '素材_懒人图库', 'http://www.lanrentuku.com/psd/anniu/5992.html', '', NULL, 1, 1, 2048, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002049, 2030, '站长素材 - 音效', 'http://sc.chinaz.com/yinxiao/', '', NULL, 1, 1, 2049, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002050, 2030, '网页模版', 'http://www.templatesy.com/', '', NULL, 1, 1, 2050, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002051, 2030, 'Iconfont-阿里巴巴矢量图标库', 'http://www.iconfont.cn/', '', NULL, 1, 1, 2051, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002052, 2030, 'undraw-矢量图标库', 'https://undraw.co/illustrations', '图标可自选色', NULL, 1, 1, 2052, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002053, 2030, 'Fontello-图标库', 'http://fontello.com', '', NULL, 1, 1, 2053, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002054, 2030, 'Flatlcon-免费的SVG、PNG、WebFont 格式图标素材', 'http://flaticons.net', '', NULL, 1, 1, 2054, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002055, 2030, 'EasyIcon-免费搜索图标的搜索引擎站点', 'http://www.easyicon.net', '', NULL, 1, 1, 2055, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002056, 2030, 'Swifticons-高品质图标素材库', 'http://www.swifticons.com', '', NULL, 1, 1, 2056, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002057, 2030, 'Icons8-提供免费iOS、Windows、Android的平面化设计图案的搜索引擎', 'https://icons8.com/', '', NULL, 1, 1, 2057, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002058, 2030, 'vexels-免费素材涵盖的范围也非常的广', 'https://www.vexels.com/', '', NULL, 1, 1, 2058, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002059, 2030, 'Vector Me-免费矢量素材网站', 'http://vector.me/', '', NULL, 1, 1, 2059, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002060, 2030, 'Freeepik', 'http://t.cn/zjw6jrk', '', NULL, 1, 1, 2060, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002061, 2030, 'Subtle Pattern 是目前特别受欢迎的纹理网站', 'http://t.cn/RJhxpBo', '', NULL, 1, 1, 2061, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002062, 2030, '1001 Free Downloads 是一个综合性的网站', 'http://www.1001freedownloads.com/', '', NULL, 1, 1, 2062, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002063, 2030, 'Vecteezy 是一个免费的矢量图索引站点', 'https://www.vecteezy.com/', '', NULL, 1, 1, 2063, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002074, 2002, '周榜--音悦Tai', 'http://vchart.yinyuetai.com/vchart/v', '', NULL, 1, 1, 2074, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002075, 2002, '推荐音乐 -- SongTaste 用音乐倾听彼此', 'http://www.songtaste.com/music/', '', NULL, 1, 1, 2075, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002076, 2002, '6V电影', 'https://www.66s.cc/', '', NULL, 1, 1, 2076, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002077, 2002, '电影票房排行榜', 'http://58921.com/alltime', '', NULL, 1, 1, 2077, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002078, 2002, '电影先生', 'http://DianYing.im', '', NULL, 1, 1, 2078, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002079, 2002, '饭团影院', 'https://fantuan.tv/vodtype/1.html', '', NULL, 1, 1, 2079, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002080, 2002, '飘花电影下载', 'https://www.piaohua.com/', '', NULL, 1, 1, 2080, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002081, 2002, '福利吧', 'http://lao4g.com', '', NULL, 1, 1, 2081, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002082, 2002, '无损音乐下载', 'https://www.sq688.com/', '', NULL, 1, 1, 2082, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002083, 2003, 'PC6 Mac软件', 'http://www.pc6.com/mac/', '', NULL, 1, 1, 2083, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002084, 2003, '史蒂芬周的博客 - Mac软件', 'http://www.sdifen.com/', '', NULL, 1, 1, 2084, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002085, 2003, '软件学堂', 'http://www.xue51.com/apple/index.html', '', NULL, 1, 1, 2085, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002086, 2003, '精品Mac应用分享推荐 - Awesome Mac', 'http://wangchujiang.com/awesome-mac/index.zh.html', '', NULL, 1, 1, 2086, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002087, 2003, '知您网(zhinin.com) - Mac软件下载', 'http://www.zhinin.com/', '', NULL, 0, 0, 2087, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002088, 2003, 'macwk - 无需积分', 'https://www.macwk.com/', '', NULL, 0, 0, 2088, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002089, 2003, 'MacEnjoy - Mac软件下载', 'https://www.macenjoy.co/', '', NULL, 1, 1, 2089, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002090, 2003, '我爱Mac - Mac软件下载', 'https://www.52mac.com/', '', NULL, 1, 1, 2090, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002091, 2003, '软件sOS - 软件下载', 'https://www.rjsos.com/', '', NULL, 1, 1, 2091, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002092, 2003, 'MAC萌新 - Mac软件下载', 'https://www.macxin.com/archives/3372.html', '', NULL, 1, 1, 2092, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002093, 2003, 'Digit77', 'https://www.digit77.com/', '', NULL, 1, 1, 2093, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002094, 2003, '马可波罗 - Mac软件下载', 'https://www.macbl.com/', '', NULL, 1, 1, 2094, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002095, 2003, 'xclient.info - Mac软件下载', 'https://xclient.info/', '', NULL, 1, 1, 2095, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002096, 2003, '潘多拉盒子 - Mac软件下载', 'https://www.inpandora.com/', '', NULL, 1, 1, 2096, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002097, 2003, 'MacYY - Mac软件下载', 'https://www.macyy.cn/', '', NULL, 1, 1, 2097, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002098, 2003, '俄罗斯的，可切换中文 - Mac软件下载', 'https://appstorrent.ru/', '', NULL, 1, 1, 2098, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002099, 2003, 'Cmarked - Mac软件下载', 'https://apps.cmacked.com/', '', NULL, 1, 1, 2099, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002100, 2003, 'Mac App - Mac软件下载', 'https://macapp.org.cn/', '', NULL, 1, 1, 2100, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002101, 2003, 'TorrentMac - Mac软件下载', 'https://www.torrentmac.net/', '', NULL, 1, 1, 2101, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002102, 2003, '优美图', 'http://www.topit.me/', '', NULL, 1, 1, 2102, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002103, 2003, '极简插件 - Chrome插件下载', 'https://chrome.zzzmh.cn/', '', NULL, 1, 1, 2103, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002104, 2003, 'Remove Video Background', 'https://www.unscreen.com/', '', NULL, 1, 1, 2104, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002105, 2003, 'Photoshop online', 'https://www.photopea.com/', '', NULL, 1, 1, 2105, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002106, 2003, '搜索导航', 'http://bt-mao.com/', '', NULL, 1, 1, 2106, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002107, 2003, '阿雷导航', 'https://aleikeji.com/mac', '', NULL, 1, 1, 2107, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002109, 2003, 'zd423 - 软件分享平台', 'http://www.zdfans.com', '', NULL, 1, 1, 2109, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002110, 2003, '绿软分享吧', 'http://www.lrshare.com', '', NULL, 1, 1, 2110, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002111, 2003, '软件缘 - 精品绿软', 'https://www.appcgn.com', '', NULL, 1, 1, 2111, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002112, 2003, '风刑软件站', 'http://www.wsf1234.com', '', NULL, 1, 1, 2112, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002113, 2003, '『BhVip』android破解软件更新合集', 'http://pan.lanzou.com/u/%E5%BD%AA%E7%85%8Cqq1846055318', '', NULL, 1, 1, 2113, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002114, 2003, 'win&android破解软件', 'https://hrtsea.com/category/android', '', NULL, 1, 1, 2114, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002115, 2003, '搞机师兄', 'https://www.lanzous.com/b904045', '', NULL, 1, 1, 2115, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002116, 2003, '网站导航', 'https://imyshare.com/navigation/', '', NULL, 1, 1, 2116, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002117, 2003, '软件学堂 - visual studio下载', 'http://www.xue51.com/soft/18137.html', 'visual studio下载', NULL, 1, 1, 2117, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002118, 2003, '极光下载 - visual studio（带注册码）', 'http://www.xz7.com/downinfo/398522.html', 'visual studio下载', NULL, 1, 1, 2118, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002119, 2004, 'U盘启动盘制作工具,U盘启动系统,大白菜.装机专家！', 'http://www.winbaicai.com/u.html', '', NULL, 1, 1, 2119, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002120, 2004, '系统之家', 'http://www.xitongzhijia.net/', '', NULL, 1, 1, 2120, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002121, 2005, '登录-学信网', 'https://account.chsi.com.cn/passport/login', '', NULL, 1, 1, 2121, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002122, 2005, '深圳市公安局出入境便民网', 'http://www.szga.gov.cn/MSJW/', '', NULL, 1, 1, 2122, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002123, 2005, '美食杰 - 美食_菜谱大全_食谱_美食网', 'http://www.meishij.net/', '', NULL, 1, 1, 2123, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002124, 2005, '麦库记事', 'https://note.sdo.com/my', '', NULL, 1, 1, 2124, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002131, 2143, '123小说网', 'https://www.banzhu77777777.net/', '', '', 1, 1, 5, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002132, 2143, 'www.eves-long.com', 'https://www.eves-long.com/', '', '', 1, 1, 5, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002133, 2143, 'MissAV - 免费观看日本AV，JAV在线高清', 'https://missav.vc/cn', '在线观看JAV，免费观看日本AV高清。', 'https://missav.vc/cache/2fad7247bf4afd916052a2af5e9631de43122a.png', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002135, 2134, '黑马磁力搜索', 'https://heimacili.org/', '', NULL, 1, 1, 1, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002137, 2125, '福利吧', 'https://fuliba2023.net/', '福利吧（fuliba2023）分享你的福利吧，每日更新福利汇总、电影推荐、购物网赚、美图摄影等精彩内容，发现更多有趣实用的网络福利。', 'https://fuliba2023.net/favicon-portal.ico', 1, 1, 2, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002138, 2134, 'NGZ南歌 Mods Share | Link3', 'https://link3.cc/zhejian', '欢迎来到导航页，有问题联系邮箱：
xnzyw6@gmail.com
南歌的小窝：www.nan2025.com
新TG频道已创建，之前的被小狗搞没了', 'https://link3.cc/favicon.ico', 1, 1, 5, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002139, 2126, 'SeedHub影视', 'https://sidhub.cc', '', 'https://sh1.pcie.pppoe.top/static/img/favicon.ico', 1, 1, 3, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002141, 2140, 'EMQX Cloud', 'https://cloud.emqx.com/console/subusers/18919008/signin', '阿里云EMQX', 'https://cloud.emqx.com/console/favicon.ico', 1, 1, 2, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002142, 2143, 'Gif动图', 'https:/www.yygif.com', '', '', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002144, 2143, '911爆料', 'https://www.wiuluoekd.cc/', '', 'https://www.wiuluoekd.cc/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002145, 2143, 'AI短剧', 'https://shorttv.online/rank', '', '', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002146, 2143, '網紅福利 - 網紅收費福利 KOL Selfie Porn - CableAV', 'https://cableav.info/category/5/', '网红不雅视频流出，例如：SVIP收费福利、微博女神、国模写真、网红女神、网红嫩模、网红模特、外围女、PR社、福利姬、网红少女、写真福利、宅男福利。', 'https://cableav.info/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002147, 2143, '小黄鸟', 'https://xiaohuangniao.me/', '要梯子', '', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002148, 2140, '物联网充装管理系统', 'http://i.117915.com', '', '', 1, 1, 1, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002149, 2140, '物联网流量卡', 'https://www.wxkjwlw.com/#/login', '物联网流量卡', 'https://www.wxkjwlw.com', 1, 1, 3, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002150, 2125, '今日热榜', 'https://tophub.today/c/tech', '今日热榜提供各站热榜聚合：微信、今日头条、百度、知乎、V2EX、微博、贴吧、豆瓣、天涯、虎扑、Github、抖音...追踪全网热点、简单高效阅读。', 'https://tophub.today/favicon.ico', 1, 1, 3, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002151, 2125, 'JRKAN直播', 'http://www.jrs0.com/', '', 'http://www.jrs0.com/favicon.ico', 1, 1, 3, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002152, 2134, '美国免税地址生成器', 'https://usaddressgen.com/tax-free-address/', '免费生成美国免税州地址，避免缴纳美国销售税。支持阿拉斯加、特拉华、蒙大拿、新罕布什尔和俄勒冈五大免税州。', 'https://usaddressgen.com/images/logo.svg', 1, 1, 5, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002153, 2127, 'Porter的个人博客', 'https://potoh.com/', '在数字世界，信息差就是护城河。我的频道就是为你推开那扇连接全球资源的门。专注于研究：海外手机号、Web3与加密货币、VPS、Ai测评与订阅、实用软件分享，Porter 不生产信息，我只打通你与世界之间的最后一百米。', 'https://potoh.com/favicon/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002154, 2127, 'NodeLoc', 'https://www.nodeloc.com/', '自由、平等、友好、开放、有趣的互联网交流社区', 'https://www.nodeloc.com/uploads/default/optimized/3X/9/7/97e15b69877e16e924a41f44d9bf73b6cd502a1c_2_32x32.png', 1, 1, 1, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002155, 2125, '小红书去水印', 'https://tools.94bug.top/tools/xhs.html', '', 'https://www.xiaohongshu.com/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002156, 2134, '『Viper』软件更新合集 - 蓝奏云', 'https://bhvip.lanzoux.com/u/%E5%BD%AA%E7%85%8CQQ1846055318', '', 'https://bhvip.lanzoux.com/favicon.ico', 1, 1, 5, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002157, 2127, 'hongxingyun.help', 'https://hongxingyun.help/', '', NULL, 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002159, 2158, 'Sublink Worker - 订阅链接转换工具', 'https://sublink.9006.de5.net/', 'Convert and optimize your subscription links easily', 'https://sublink.9006.de5.net/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002160, 2158, '提醒.订阅管理系统', 'https://subs.9006.de5.net/', '', 'https://subs.9006.de5.net/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002161, 2134, '免费视频去水印下载工具 - 抖音B站视频图片解析下载 - 效率坊解析工具', 'https://www.xiaolvfang.com/', '效率坊视频解析工具，支持下载抖音、B站、YouTube、TikTok等上千个平台站点的视频图片。一键解析即可免费去除水印，快速将高清无水印视频图片保存至电脑或手机。', 'https://www.xiaolvfang.com/img/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002162, 2134, '牛蛙助手安装及使用 | Yiov', 'https://yiov.top/iPhone/sign/bullfrog', '敏而好学，不耻下问', 'https://yiov.top/logo.png', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002163, 2127, 'rectg - Telegram 中文资源索引', 'https://www.rectg.com/', '收录 530 个 Telegram 中文频道、群组和机器人，按主题整理公开资源，支持分类浏览、关键词搜索和详情查看。', 'https://www.rectg.com/favicon.png', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002164, 2127, '源仓库最新地址 | Link3', 'https://link3.cc/yckceo', '源仓库地址引导，发布页', 'https://link3.cc/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002165, 2134, '电视盒子源', 'https://cyuan.netlify.app/', '', 'https://cyuan.netlify.app/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002166, 2143, 'JAV字幕 | 日本AV & 欧美影片中文字幕下载', 'https://javzimu.com/', '专业的AV中文字幕搜索引擎，提供最新FC2、S1、Moodyz等厂商的影片字幕下载。支持番号搜索，一键下载SRT/ASS字幕文件，无需注册，永久免费。', 'https://javzimu.com/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002167, 2143, '激情小说小说_超好看的激情小说小说_2026激情小说小说排行榜-新笔趣阁', 'https://www.bqgns.com/jq', '笔趣阁是广大书友最值得收藏的小说阅读网,收录了当前最火热的小说最新章节,笔趣阁免费提供高质量的无弹窗小说,是广大小说爱好者必备的小说阅读网', 'https://www.bqgns.com/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002168, 2143, '总点击榜-PO18全本_自由的小说阅读网', 'https://www.po18m.com/top.html', 'PO18全本 集合在线原创、在线免费阅读、线上发布的专属文学服务平台。', 'https://www.po18m.com/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002169, 2143, 'Archive - 探花万人迷', 'https://tanhuawanrenmi.github.io/archive/?tag=%E8%BF%94%E5%9C%BA%E5%A5%B3%E7%A5%9E', '探花万人迷', 'https://tanhuawanrenmi.github.io/img/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002170, 2126, 'Moovie 影牛 - 发现你的下一部电影', 'https://moovie.c2v2.com/', 'Moovie 影牛是一个全网影视聚合搜索网站，支持一键搜索各大资源平台的电影、电视剧和综艺节目，让你轻松找到想看的影片。', 'data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐮</text></svg>', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002171, 2126, '2025最新热门短剧大全免费观看全集_高清无广告抖音快手红果爆款微短剧-红果果短剧网', 'https://www.hongguoguo.tv/', '(Description)红果果短剧网2025最新短剧免费观看平台，每日更新霸总追妻火葬场、甜宠先婚后爱、赘婿战神归来、穿越重生、复仇虐渣、古装仙侠等上千部抖音快手红果爆款微短剧，全集高清完整版无广告竖屏在线看，一次性看全集不追更，短剧爱好者最爱！', 'https://www.hongguoguo.tv/template/Naifei/static/img/favicon.png', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002172, 2143, 'whos.tv', 'https://whos.tv/', '', NULL, 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002174, 2134, '【免费】2026 小火箭共享账号 | 美区ID / 苹果ID共享 (已购Shadowrocket) - 翻墙男', 'https://fanqiangnan.com/appleid.html', '2026实时更新的小火箭共享账号，提供已购 Shadowrocket 的美区ID（苹果ID），并覆盖港区、日区、台区等地区账号，支持直接登录下载使用。账号每30分钟自动检测更新，一键复制即用，稳定可用。免费获取苹果ID，认准翻墙男。', 'https://fanqiangnan.com/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002175, 2134, '视频下载工具 - 全网视频无水印解析下载', 'https://downloadhd.net/', '支持全网主流平台视频无水印解析下载，包括 YouTube、TikTok、Instagram、Bilibili 等。免费在线视频下载器，无需安装软件。', 'https://downloadhd.net/Favicon01_converted.webp', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002177, 2134, 'FongMi蜂蜜版电视tvbox盒子APK（持续更新） - 黑海洋Wiki | AI机器人硬件开发 | 网络安全攻防实战 | 区块链技术文档教程 - 免费资源平台', 'https://blog.upx8.com/3385/comment-page-2#comments', 'FongMi版的独家优势 1、FongMi版刚开发前几版的时候就有安装体验，因为它只出TV版，所以，安卓手机上体验还是感觉也不是太出众；另外，电视直播功能也是最近才支持，最开始是不支持的； 2、目前的版本已经相当完善了，没有类似TVbox于俊版那样花里花哨的鸡肋功能，非常极简。其实，使用FongMi版的用户，只需要了解...', 'https://blog.upx8.com/usr/uploads/logo.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002178, 2126, '购物 - GetAcc', 'https://getacc.shop/', '', 'https://getacc.shop/favicon.ico?v=3.4.9', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002179, 2126, '源仓库', 'https://www.yck2026.top/', '', 'https://www.yck2026.top/favicon.ico', 1, 1, 4, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002180, 2134, '紫罗兰工具箱 - VioletToolBox | 免费全能的Android刷机工具', 'https://violettool.top/', '紫罗兰工具箱(VioletToolBox)是一款免费多功能的Android手机刷机工具，支持小米、OPPO、一加、真我等机型线刷、救砖、全自动投屏、一键ROOT，Twrp刷机，合并Super等60+强大功能。', 'https://violettool.top/images/favicon.ico', 1, 1, 6, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);

-- Migration SQL script generation completed.