-- ========================================================
-- Auto-generated data migration from legacy python sitenav
-- Generated At: 2026-07-17T09:34:25.921Z
-- ========================================================

-- Clean legacy table data for idempotency
DELETE FROM sites;
DELETE FROM categories;

-- Seed D1 AUTOINCREMENT floor for sites table (10,000,000)
INSERT INTO sites (id, category_id, name, url, status) VALUES (9999999, NULL, '__seed_floor__', 'about:blank', 0);
DELETE FROM sites WHERE id = 9999999;

-- ========================================================
-- PHASE 0: Create the index/other/h5 root buckets
-- These are real category rows (pid IS NULL) that the v1 adapter layer
-- reads back via name, replacing the old rootId>=2000 ID-threshold guess.
-- No explicit id: on a freshly emptied table these autoincrement to 1/2/3,
-- which never collides with the preserved legacy ids (1000+/2000+) below.
-- ========================================================

INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'index', 0, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'other', 1, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (NULL, 'h5', 2, 1, 1, 1, strftime('%s', 'now') * 1000);

-- ========================================================
-- PHASE 1: Populate categories (preserving original raw IDs)
-- Top-level rows (original pId = 0) are reparented under the matching
-- index/other root created in PHASE 0 instead of staying pid = NULL.
-- ========================================================

INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1000, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Common Sites', 1000, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1100, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Local Sites', 1100, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1200, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Dev20 Sites', 1200, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1210, 1200, 'develop', 1210, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1220, 1200, 'QA', 1220, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1300, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Test Sites', 1300, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (1400, (SELECT id FROM categories WHERE name = 'index' AND pid IS NULL LIMIT 1), 'Prod Sites', 1400, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2000, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '常用', 2000, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2001, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '学习', 2001, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2002, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '影视', 2002, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2003, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '杂类', 2003, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2004, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '系统', 2004, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2005, (SELECT id FROM categories WHERE name = 'other' AND pid IS NULL LIMIT 1), '生活', 2005, 1, 0, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2022, 2001, '代码仓库， 免费建站', 2022, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2026, 2001, 'Database', 2026, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2027, 2001, 'Mock Api', 2027, 1, 1, 1, strftime('%s', 'now') * 1000);
INSERT INTO categories (id, pid, name, sort_order, is_public, is_expand, status, created_at) VALUES (2030, 2001, '音图资源', 2030, 1, 1, 1, strftime('%s', 'now') * 1000);

-- ========================================================
-- PHASE 2: Populate sites (applying SITE_ID_OFFSET = 10000000)
-- ========================================================

INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001010, 1000, 'Jenkins', 'http://121.196.104.20:8888/', '', NULL, 1, 1, 1010, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001020, 1000, '禅道', 'http://192.168.2.180:82/zentao/my.html', '', NULL, 1, 1, 1020, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001030, 1000, '墨刀', 'https://modao.cc/team/splbgnpgz7muqiei/folder/tel2zzhemdlh8vgayk', '', NULL, 1, 1, 1030, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001040, 1000, '邮箱', 'http://mail.lanyang.com/', '', NULL, 1, 1, 1040, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001050, 1000, 'Gitblit', 'http://192.168.2.180:8808/', '', NULL, 1, 1, 1050, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001060, 1000, '开发任务汇总', 'https://www.kdocs.cn/wo/sl/v344KoRZ?app_id=2wd4E4bxTOHihwkwkvaNGN', '', NULL, 1, 1, 1060, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001070, 1000, '物联网秤项目任务', 'https://kdocs.cn/l/cogElwjqE2yZ', '', NULL, 1, 1, 1070, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001080, 1000, '发布申请表', 'https://kdocs.cn/l/crwpEMnJI6Lt', '', NULL, 1, 1, 1080, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001110, 1100, 'IotLpg.Web', 'http://localhost:8012/IotLpg.Web/index.aspx', '', NULL, 1, 1, 1110, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001120, 1100, 'IotLpg.Sale.App.Api', 'http://localhost:8012/iot.sale.app.api/swagger/index.html', '', NULL, 1, 1, 1120, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001130, 1100, 'IotLpg.Sale.App.Api(Sejil Log)', 'http://localhost:8012/iot.sale.app.api/Sejil', '', NULL, 1, 1, 1130, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001140, 1100, 'trunklpg', 'http://localhost:8012/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1140, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001150, 1100, 'trunklpg - 呼叫配送管理系统', 'http://localhost:8012/dev.trunklpg/SysManage/index.aspx', '', NULL, 1, 1, 1150, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001160, 1100, '09WebAPI.WebApi', 'http://localhost:8012/dev.webapi/swagger', '', NULL, 1, 1, 1160, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001170, 1100, 'SaaSAPPlpg', 'http://localhost:8012/dev.saasapplpg', '', NULL, 1, 1, 1170, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001180, 1100, 'OperationLogs', 'http://localhost:8012/dev.trunklpg/SaasHTML5/System/OperationLogs.html', '', NULL, 1, 1, 1180, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001211, 1210, 'dev.trunklpg', 'https://test.117915.com/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1211, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001212, 1210, 'dev.webapi', 'https://test.117915.com/dev.webapi/swagger', '', NULL, 1, 1, 1212, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001213, 1210, 'dev.saasapplpg', 'https://test.117915.com/dev.saasapplpg/', '', NULL, 1, 1, 1213, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001221, 1220, 'dev.trunklpg', 'http://121.196.104.20:8013/dev.trunklpg/home/default.aspx', '', NULL, 1, 1, 1221, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001222, 1220, 'dev.webapi', 'http://121.196.104.20:8013/dev.webapi/swagger', '', NULL, 1, 1, 1222, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001223, 1220, 'dev.saasapplpg', 'http://121.196.104.20:8013/dev.saasapplpg/', '', NULL, 1, 1, 1223, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001310, 1300, 'iotlpg', 'http://iotlpg.117915.com/testclient/Login.aspx', '', NULL, 1, 1, 1310, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001320, 1300, 'iotlpg.saleapp.api', 'https://iotlpg.117915.com/iot.weigh.webapi.testsaleapp/swagger/index.html', '', NULL, 1, 1, 1320, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001330, 1300, '气瓶安全信息化管理系统', 'http://www.117915.cn:99/', '', NULL, 1, 1, 1330, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001340, 1300, 'trunklpg', 'https://lpg.117915.com/testlpg/home/default.aspx', '', NULL, 1, 1, 1340, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001350, 1300, 'trunklpg.SysManage', 'https://lpg.117915.com/testlpg/sysmanage/index.aspx', '', NULL, 1, 1, 1350, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001410, 1400, 'iotlpg', 'http://iotlpg.117915.com/client/Login.aspx', '', NULL, 1, 1, 1410, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001420, 1400, 'iotlpg.saleapp.api', 'https://iotlpg.117915.com/iot.weigh.webapi.saleapp/swagger/index.html', '', NULL, 1, 1, 1420, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001430, 1400, 'iotlpg.saleapp.api logs', 'https://iotlpg.117915.com/iot.weigh.webapi.saleapp/sejil', '', NULL, 1, 1, 1430, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001440, 1400, 'dcc.PublishCompConnChanged', 'http://iotlpg.117915.com/iot.weigh.dcc/Ajax/DccClient/PublishCompConnChanged.ashx', '', NULL, 1, 1, 1440, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001450, 1400, 'trunklpg', 'https://lpg.117915.com/lpg/Login.aspx', '', NULL, 1, 1, 1450, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10001460, 1400, 'trunklpg.SysManage', 'https://lpg.117915.com/lpg/sysmanage/index.aspx', '', NULL, 1, 1, 1460, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002006, 2000, '电影推荐 · MVCAT', 'https://www.mvcat.com/', '', NULL, 1, 1, 2006, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002008, 2000, '编程工具', 'https://masuit.com/cat/7', '', NULL, 1, 1, 2008, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002009, 2000, 'Software - 厘米天空', 'http://www.cmsky.com/', '', NULL, 1, 1, 2009, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002010, 2000, '吾爱破解', 'https://www.52pojie.cn/', 'dfg727/aB...6', NULL, 1, 1, 2010, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002011, 2000, '图怪兽作图神器', 'https://818ps.com/', '是一个在线ps图片 海报 编辑器,', NULL, 1, 1, 2011, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002013, 2000, '书享家', 'http://shuxiangjia.cn/', '', NULL, 1, 1, 2013, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002015, 2000, 'fuliba', 'https://fuliba2023.net', '搞笑图', NULL, 1, 1, 2015, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002017, 2000, '远景', 'http://bbs.pcbeta.com/', 'ifelse01/Aa123456', NULL, 1, 1, 2017, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002018, 2000, '威锋', 'https://bbs.feng.com/', '1581.../aB...', NULL, 1, 1, 2018, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002020, 2000, 'ClashNode', 'https://clashfree.eu.org/', '', NULL, 1, 1, 2020, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002021, 2001, 'Net Framework', 'https://www.microsoft.com/net/download/visual-studio-sdks/', '', NULL, 1, 1, 2021, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002032, 2022, '免费建站 - 基于github...', 'https://app.netlify.com/account/sites', '', NULL, 1, 1, 2032, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002033, 2022, 'CodeSandbox - 托管编码平台', 'https://codesandbox.io/', '', NULL, 1, 1, 2033, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002034, 2022, 'glitch - 托管编码平台', 'https://glitch.com/', '', NULL, 1, 1, 2034, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002035, 2022, 'replit - 托管编码平台', 'https://replit.com/', '', NULL, 1, 1, 2035, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002036, 2022, 'RiouxSVN', 'https://riouxsvn.com', '', NULL, 1, 1, 2036, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002037, 2022, 'SourceForge.net', 'https://sourceforge.net/account/login.php', '', NULL, 1, 1, 2037, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002038, 2022, 'codeplex.com', 'https://workspaces.codeplex.com/SourceControl/latest', '', NULL, 1, 1, 2038, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002039, 2022, 'ifelse01  GitHub', 'https://github.com/ifelse01', '', NULL, 1, 1, 2039, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002040, 2022, '代码托管 - 开源中国社区', 'https://git.oschina.net/ifelse01', '', NULL, 1, 1, 2040, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002023, 2001, 'sendgrid', 'https://app.sendgrid.com/login', 'ifelse01/abc..@123..', NULL, 1, 1, 2023, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002024, 2001, 'CSDN论坛', 'http://forum.csdn.net/BList/DotNET/EssentialList', 'abc..@123..', NULL, 1, 1, 2024, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002025, 2001, 'dfg727 博客园', 'http://www.cnblogs.com/dfg727/', '', NULL, 1, 1, 2025, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002041, 2026, 'JackDB - 在线各种数据库', 'https://app.jackdb.com/', 'QQ Login', NULL, 1, 1, 2041, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002042, 2026, 'db4free.net  MySQL', 'http://db4free.net/d4f_apply.php', '', NULL, 1, 1, 2042, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002043, 2026, '云数据库 - Bmob', 'http://www.bmob.cn/', '', NULL, 1, 1, 2043, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002044, 2027, 'DOClever', 'http://doclever.cn/controller/index/index.html', 'dfg727', NULL, 1, 1, 2044, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002045, 2027, 'rap2-taobao', 'rap2.taobao.org', '2167162@qq.com', NULL, 1, 1, 2045, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002046, 2027, 'easy-mock', 'https://www.easy-mock.com', '', NULL, 1, 1, 2046, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002028, 2001, 'ProcessOn - 在线作图', 'https://www.processon.com/', 'QQ Login', NULL, 1, 1, 2028, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002029, 2001, 'BootCDN - 在CDN 加速服务', 'https://www.bootcdn.cn/', '前端开源项目 CDN 加速服务 ', NULL, 1, 1, 2029, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002047, 2030, '好图网 - 提供最优秀的图标下载', 'http://www.haotu.net/icon/179594/todo', '', NULL, 1, 1, 2047, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002048, 2030, '素材_懒人图库', 'http://www.lanrentuku.com/psd/anniu/5992.html', '', NULL, 1, 1, 2048, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002049, 2030, '站长素材 - 音效', 'http://sc.chinaz.com/yinxiao/', '', NULL, 1, 1, 2049, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002050, 2030, '网页模版', 'http://www.templatesy.com/', '', NULL, 1, 1, 2050, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002051, 2030, 'Iconfont-阿里巴巴矢量图标库', 'http://www.iconfont.cn/', '', NULL, 1, 1, 2051, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002052, 2030, 'undraw-矢量图标库', 'https://undraw.co/illustrations', '图标可自选色', NULL, 1, 1, 2052, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002053, 2030, 'Fontello-图标库', 'http://fontello.com', '', NULL, 1, 1, 2053, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002054, 2030, 'Flatlcon-免费的SVG、PNG、WebFont 格式图标素材', 'http://flaticons.net', '', NULL, 1, 1, 2054, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002055, 2030, 'EasyIcon-免费搜索图标的搜索引擎站点', 'http://www.easyicon.net', '', NULL, 1, 1, 2055, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002056, 2030, 'Swifticons-高品质图标素材库', 'http://www.swifticons.com', '', NULL, 1, 1, 2056, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002057, 2030, 'Icons8-提供免费iOS、Windows、Android的平面化设计图案的搜索引擎', 'https://icons8.com/', '', NULL, 1, 1, 2057, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002058, 2030, 'vexels-免费素材涵盖的范围也非常的广', 'https://www.vexels.com/', '', NULL, 1, 1, 2058, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002059, 2030, 'Vector Me-免费矢量素材网站', 'http://vector.me/', '', NULL, 1, 1, 2059, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002060, 2030, 'Freeepik', 'http://t.cn/zjw6jrk', '', NULL, 1, 1, 2060, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002061, 2030, 'Subtle Pattern 是目前特别受欢迎的纹理网站', 'http://t.cn/RJhxpBo', '', NULL, 1, 1, 2061, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002062, 2030, '1001 Free Downloads 是一个综合性的网站', 'http://www.1001freedownloads.com/', '', NULL, 1, 1, 2062, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002063, 2030, 'Vecteezy 是一个免费的矢量图索引站点', 'https://www.vecteezy.com/', '', NULL, 1, 1, 2063, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002031, 2001, 'Docker 从入门到实践 Search', 'https://vuepress.mirror.docker-practice.com/image/dockerfile/', '', NULL, 1, 1, 2031, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002074, 2002, '周榜--音悦Tai', 'http://vchart.yinyuetai.com/vchart/v', '', NULL, 1, 1, 2074, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002075, 2002, '推荐音乐 -- SongTaste 用音乐倾听彼此', 'http://www.songtaste.com/music/', '', NULL, 1, 1, 2075, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002076, 2002, '6V电影', 'https://www.66s.cc/', '', NULL, 1, 1, 2076, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002077, 2002, '电影票房排行榜', 'http://58921.com/alltime', '', NULL, 1, 1, 2077, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002078, 2002, '电影先生', 'http://DianYing.im', '', NULL, 1, 1, 2078, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002079, 2002, '饭团影院', 'https://fantuan.tv/vodtype/1.html', '', NULL, 1, 1, 2079, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002080, 2002, '飘花电影下载', 'https://www.piaohua.com/', '', NULL, 1, 1, 2080, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002081, 2002, '福利吧', 'http://lao4g.com', '', NULL, 1, 1, 2081, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002082, 2002, '无损音乐下载', 'https://www.sq688.com/', '', NULL, 1, 1, 2082, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002083, 2003, 'PC6 Mac软件', 'http://www.pc6.com/mac/', '', NULL, 1, 1, 2083, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002084, 2003, '史蒂芬周的博客 - Mac软件', 'http://www.sdifen.com/', '', NULL, 1, 1, 2084, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002085, 2003, '软件学堂', 'http://www.xue51.com/apple/index.html', '', NULL, 1, 1, 2085, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002086, 2003, '精品Mac应用分享推荐 - Awesome Mac', 'http://wangchujiang.com/awesome-mac/index.zh.html', '', NULL, 1, 1, 2086, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002087, 2003, '知您网(zhinin.com) - Mac软件下载', 'http://www.zhinin.com/', '', NULL, 0, 0, 2087, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002088, 2003, 'macwk - 无需积分', 'https://www.macwk.com/', '', NULL, 0, 0, 2088, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002089, 2003, 'MacEnjoy - Mac软件下载', 'https://www.macenjoy.co/', '', NULL, 1, 1, 2089, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002090, 2003, '我爱Mac - Mac软件下载', 'https://www.52mac.com/', '', NULL, 1, 1, 2090, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002091, 2003, '软件sOS - 软件下载', 'https://www.rjsos.com/', '', NULL, 1, 1, 2091, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002092, 2003, 'MAC萌新 - Mac软件下载', 'https://www.macxin.com/archives/3372.html', '', NULL, 1, 1, 2092, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002093, 2003, 'Digit77', 'https://www.digit77.com/', '', NULL, 1, 1, 2093, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002094, 2003, '马可波罗 - Mac软件下载', 'https://www.macbl.com/', '', NULL, 1, 1, 2094, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002095, 2003, 'xclient.info - Mac软件下载', 'https://xclient.info/', '', NULL, 1, 1, 2095, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002096, 2003, '潘多拉盒子 - Mac软件下载', 'https://www.inpandora.com/', '', NULL, 1, 1, 2096, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002097, 2003, 'MacYY - Mac软件下载', 'https://www.macyy.cn/', '', NULL, 1, 1, 2097, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002098, 2003, '俄罗斯的，可切换中文 - Mac软件下载', 'https://appstorrent.ru/', '', NULL, 1, 1, 2098, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002099, 2003, 'Cmarked - Mac软件下载', 'https://apps.cmacked.com/', '', NULL, 1, 1, 2099, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002100, 2003, 'Mac App - Mac软件下载', 'https://macapp.org.cn/', '', NULL, 1, 1, 2100, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002101, 2003, 'TorrentMac - Mac软件下载', 'https://www.torrentmac.net/', '', NULL, 1, 1, 2101, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002102, 2003, '优美图', 'http://www.topit.me/', '', NULL, 1, 1, 2102, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002103, 2003, '极简插件 - Chrome插件下载', 'https://chrome.zzzmh.cn/', '', NULL, 1, 1, 2103, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002104, 2003, 'Remove Video Background', 'https://www.unscreen.com/', '', NULL, 1, 1, 2104, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002105, 2003, 'Photoshop online', 'https://www.photopea.com/', '', NULL, 1, 1, 2105, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002106, 2003, '搜索导航', 'http://bt-mao.com/', '', NULL, 1, 1, 2106, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002107, 2003, '阿雷导航', 'https://aleikeji.com/mac', '', NULL, 1, 1, 2107, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002109, 2003, 'zd423 - 软件分享平台', 'http://www.zdfans.com', '', NULL, 1, 1, 2109, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002110, 2003, '绿软分享吧', 'http://www.lrshare.com', '', NULL, 1, 1, 2110, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002111, 2003, '软件缘 - 精品绿软', 'https://www.appcgn.com', '', NULL, 1, 1, 2111, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002112, 2003, '风刑软件站', 'http://www.wsf1234.com', '', NULL, 1, 1, 2112, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002113, 2003, '『BhVip』android破解软件更新合集', 'http://pan.lanzou.com/u/%E5%BD%AA%E7%85%8Cqq1846055318', '', NULL, 1, 1, 2113, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002114, 2003, 'win&android破解软件', 'https://hrtsea.com/category/android', '', NULL, 1, 1, 2114, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002115, 2003, '搞机师兄', 'https://www.lanzous.com/b904045', '', NULL, 1, 1, 2115, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002116, 2003, '网站导航', 'https://imyshare.com/navigation/', '', NULL, 1, 1, 2116, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002117, 2003, '软件学堂 - visual studio下载', 'http://www.xue51.com/soft/18137.html', 'visual studio下载', NULL, 1, 1, 2117, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002118, 2003, '极光下载 - visual studio（带注册码）', 'http://www.xz7.com/downinfo/398522.html', 'visual studio下载', NULL, 1, 1, 2118, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002119, 2004, 'U盘启动盘制作工具,U盘启动系统,大白菜.装机专家！', 'http://www.winbaicai.com/u.html', '', NULL, 1, 1, 2119, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002120, 2004, '系统之家', 'http://www.xitongzhijia.net/', '', NULL, 1, 1, 2120, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002121, 2005, '登录-学信网', 'https://account.chsi.com.cn/passport/login', '', NULL, 1, 1, 2121, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002122, 2005, '深圳市公安局出入境便民网', 'http://www.szga.gov.cn/MSJW/', '', NULL, 1, 1, 2122, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002123, 2005, '美食杰 - 美食_菜谱大全_食谱_美食网', 'http://www.meishij.net/', '', NULL, 1, 1, 2123, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);
INSERT INTO sites (id, category_id, name, url, description, icon, status, is_public, sort_order, created_at, updated_at) VALUES (10002124, 2005, '麦库记事', 'https://note.sdo.com/my', '', NULL, 1, 1, 2124, strftime('%s', 'now') * 1000, strftime('%s', 'now') * 1000);

-- Migration SQL script generation completed.